### ISSUE TITLE
looking at a use case for dynamically enabling the limiter at run time

### ISSUE THREAD

**Issue by camallen** [parrish/Sidekiq-Congestion#2]
Basically taking some job params and making decisions to run the limiter or not, i.e. if the user is an admin then skip the limiter, etc. Sound like something you'd support?

**Comment by parrish** [comment]
Yep.  I'll look at adding it

**Comment by camallen** [comment]
sweet, i can PR if you'd like, let me know.

**Comment by parrish** [comment]
Released in [v0.0.4](https://github.com/parrish/Sidekiq-Congestion/releases/tag/v0.0.4)

**Comment by parrish** [comment]
Hmm... looks like I need to fix the dependencies.  One sec.

**Comment by parrish** [comment]
Cool.  Compatible with Sidekiq 4.0+ now.  Released in [v0.1.0](https://github.com/parrish/Sidekiq-Congestion/releases/tag/v0.1.0)

**Comment by camallen** [comment]
sweet, thanks!
